### ISSUE TITLE
Infinite loop ☝️🤓

### ISSUE THREAD

**Issue by Quentin-Clement** [HiNett/CarbonWashing#12]
Is it normal that when you choose "Be soft, launch at 30°C" then "Yes", you can be stuck in an infinite loop?

**Comment by Biohazardyee** [comment]
If you had read the plot, you'll notice that it's normal

**Comment by Quentin-Clement** [comment]
I'm dysxilec and I'm a bit dasippoineted taht nithnog has been done on porupse for poelpe like me...

**Comment by Biohazardyee** [comment]
nothing prove's that you're dislexic, just read better; L bozo + ratio

**Comment by Quentin-Clement** [comment]
plz write dyslexic correctly next time skill issue XD ;D xoxo

**Comment by Biohazardyee** [comment]
xD, stfu <3
