### ISSUE TITLE
Morse issue 

### ISSUE THREAD

**Issue by thomas-planchard** [HiNett/CarbonWashing#14]
-.-. --- ..- .-.. -.. / .. - / -... . / .--. --- ... ... .. -... .-.. . / - --- / .... .- ...- . / .- / -- --- .-. ... . / ...- . .-. ... .. --- -. / ..--..

**Comment by Biohazardyee** [comment]
··· ·− −·· ·−·· −·−−  ·· −  ·· ··· −· −  ·· −·  −−− ··− ·−·  −·· · ···− · ·−·· −−− ·−−· −− · −· −  ·−−· ·−·· ·− −·  −··· ··− −  ·−− ·  −− ·· −−· ···· −  ·− −·· −··  ·· − ·−·−·−

**Comment by thomas-planchard** [comment]
.. / -.. --- -. .----. - / ..- -. -.. . .-. ... - .- -. -.. / .-- .... .- - / -.-- --- ..- / .--- ..- ... - . / .-- .-. --- - . .-.-.- / .. / - .... .. -. -.- / -.-- --- ..- / ..- ... . -.. / .- / .-- .-. --- -. --. / -- --- .-. ... . / -.-. --- -.. .

**Comment by Biohazardyee** [comment]
··· ·− −·· ·−·· −·−− −··−·  ·· − −··−· ·· ··· −· − −··−· ·· −· −··−· −−− ··− ·−· −··−· −·· · ···− · ·−·· −−− ·−−· −− · −· − −··−· ·−−· ·−·· ·− −· −··−· −··· ··− − −··−· ·−− · −··−· −− ·· −−· ···· − −··−· ·− −·· −·· −··−· ·· − ·−·−·−
