### ISSUE TITLE
⠊ ⠍ ⠃⠇⠊⠝⠙

### ISSUE THREAD

**Issue by Quentin-Clement** [HiNett/CarbonWashing#15]
⠊ ⠉⠁⠝⠞ ⠎⠑⠑ ⠺⠕⠥⠇⠙ ⠊⠞ ⠃⠑ ⠏⠕⠎⠎⠊⠃⠇⠑ ⠞⠕ ⠓⠁⠧⠑ ⠁ ⠃⠗⠁⠊⠇⠇⠑ ⠧⠑⠗⠎⠊⠕⠝ ⠊⠝ ⠞⠓⠑ ⠋⠥⠞⠥⠗⠑ ⠏⠇⠑⠁⠎⠑

**Comment by Biohazardyee** [comment]
not working

**Comment by Quentin-Clement** [comment]
like your brain 🫳🎤

**Comment by Biohazardyee** [comment]
facts

**Comment by nusco** [comment]
Good job closing this one.
