### ISSUE TITLE
Elone has Benoit's phone and Benoit has Elone's computer 😡

### ISSUE THREAD

**Issue by Quentin-Clement** [HiNett/CarbonWashing#17]

**Comment by Biohazardyee** [comment]
We're aware of the issue, we're trying our best to solve it

**Comment by Quentin-Clement** [comment]
Thank you in advance because the noise is a bit mindblowing

**Comment by TechXplorerFR** [comment]
We understand your disappointment, our team is trying to resolve the issue and negotiate with Benoît using a Mars right away.

**Comment by Biohazardyee** [comment]
sorry for the inconvenience caused

**Comment by TechXplorerFR** [comment]
Please refer to our manual for pricing

**Comment by Quentin-Clement** [comment]
And Benoit is maybe a type 2

**Comment by TechXplorerFR** [comment]
Type 3 for sure

**Comment by Quentin-Clement** [comment]
No, don't say that, he will think he is really
Just say that he is a Type 2 ascendant chèvre d'ascenseur

**Comment by Quentin-Clement** [comment]
Hello guys sorry, I was not the one writing the previous comments, an hacker took the control of my keyboard 😹🤘
