### ISSUE TITLE
Icon bug on macOS

### ISSUE THREAD

**Issue by Clementine951** [HiNett/CarbonWashing#19]
There is a problem with the icon of your app. I can't see it.

<img width="112" alt="Screenshot 2024-02-12 at 16 53 59" src="https://github.com/HiNett/CarbonWashing/assets/78617457/676754de-5548-45ef-a6a7-d075e772bbd8">

**Comment by Biohazardyee** [comment]
This is normal as we didn't put any icon it does the same on windows!!
